baseURL = "https://butterswords.com"
title = "Butterswords | Butters Words | Butter Swords"
author = "Nathan Butters"
locale = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

[services]
  [services.googleAnalytics]
  # If you're using Google Analytics, you can enable this feature.
  #id = "G-1234567890"

[params]
showBlog = true
mainSections = ['blog']
googleFonts = true

  [params.logo]
  main = "img/logo/logo.svg"
  alt = "butterswords logo"

  # The size parameter is the class name of tailwindcss
  # https://tailwindcss.com/
  size = "h-14"

  [params.site]
  name = "Navigating tradeoffs in safety and value in system development."

  [params.icon]
  # If you want to use FontAwesome, set this parameter to true.
  fontawesome = true

  # You can also use Bootstrap Icons.
  bootstrap = true

  [params.share]
  # If you want to use share buttons, set this parameter to true.
  enable = true
  # Uncomment and edit to limit which services are shown
  # services = ["twitter", "mastodon", "facebook", "line", "linkedin", "whatsapp", "mail", "copy"]

  [params.homepage_meta_tags]
  meta_description = "Navigating tradeoffs between safety and value in system development."
  meta_og_title = "Butterswords | Butters Words | Butter Swords"
  meta_og_type = "website"
  meta_og_url = "http://butterswords.com"
  meta_og_image = "img/logo/logo.svg"
  meta_og_description = "Navigating tradeoffs between safety and value in system development."

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

 # [[menu.main]]
 # identifier = "products"
 # name = "Products"
 # url = "/products/"
 # weight = 3

 # [[menu.main]]
 # identifier = "services"
 # name = "Services"
 # url = "/services/"
 # weight = 4

  [[menu.main]]
  identifier = "bookshelf"
  name = "Bookshelf"
  url = "/bookshelf/"
  weight = 5

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 6

  # Footer Menu
  [[menu.footer]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  url = "/blog"
  weight = 2

  [[menu.footer]]
  name = "Linkedin"
  url = "https://linkedin.com/in/nathanbutters"
  pre = "<i class='bi bi-linkedin text'></i>"
  weight = 2

  [[menu.footer]]
  name = "Github"
  url = "https://github.com/butterswords"
  pre = "<i class='bi bi-github text'></i>"
  weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
  disabled = false
  simple = false

  [privacy.x]
  disabled = false
  enableDNT = true
  simple = false

  [privacy.instagram]
  disabled = false
  simple = false

  [privacy.youtube]
  disabled = false
  privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[build]
  [build.buildStats]
  enable = true
  [[build.cachebusters]]
  source = 'assets/notwatching/hugo_stats\.json'
  target = 'css'

[module]
  [[module.mounts]]
  source = 'assets'
  target = 'assets'
  [[module.mounts]]
  disableWatch = true
  source = 'hugo_stats.json'
  target = 'assets/notwatching/hugo_stats.json'
